version: '3.9'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "8000:80"
      depends_on:
        - web
      volumes:
        - ./nginx:/etc/nginx/conf.d
      networks:
        - default

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: >
      bash -c "
      chmod +x /app/wait-for-it.sh &&
      /app/wait-for-it.sh -t 5 ${DB_HOST}:${DB_PORT} -- &&
      psql -h ${DB_HOST} -U ${DB_USER} -c 'CREATE DATABASE ${DB_NAME}' || true &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432

  db:
    container_name: postgres_db
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  default:
    name: django_network